/* ==========================================================================
   File: tailwind.config.js
   Tujuan: Menyediakan design tokens Tailwind untuk typography, warna, spacing, dan radius portfolio.
   Dipakai oleh: index.html via Tailwind CDN config hook.
   Dependensi utama: Tailwind CDN runtime.
   Fungsi public/utama: Mengekspos global `tailwind.config`.
   Side effect penting: Mengubah utility class yang tersedia saat page dirender.
   ========================================================================== */

tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-container-high":     "#e9e8e7",
                "surface-dim":                "#dbdad9",
                "surface-tint":               "#5f5e5e",
                "error":                      "#ba1a1a",
                "on-primary-container":       "#858383",
                "inverse-on-surface":         "#f2f0f0",
                "tertiary":                   "#000000",
                "on-secondary":               "#ffffff",
                "inverse-primary":            "#c8c6c5",
                "on-surface-variant":         "#444748",
                "on-tertiary-fixed":          "#261900",
                "on-tertiary":                "#ffffff",
                "on-secondary-fixed-variant": "#464745",
                "primary":                    "#000000",
                "tertiary-fixed-dim":         "#e9c176",
                "error-container":            "#ffdad6",
                "on-secondary-fixed":         "#1a1c1a",
                "on-error-container":         "#93000a",
                "surface-container-low":      "#f5f3f3",
                "on-secondary-container":     "#626361",
                "outline":                    "#747878",
                "surface":                    "#fbf9f8",
                "surface-container-lowest":   "#ffffff",
                "on-tertiary-fixed-variant":  "#5d4201",
                "on-tertiary-container":      "#a17f3b",
                "on-background":              "#1b1c1c",
                "secondary-container":        "#e0e0dd",
                "surface-container":          "#efeded",
                "on-error":                   "#ffffff",
                "on-primary":                 "#ffffff",
                "primary-container":          "#1c1b1b",
                "outline-variant":            "#c4c7c7",
                "surface-container-highest":  "#e4e2e2",
                "secondary-fixed":            "#e3e2df",
                "background":                 "#fbf9f8",
                "primary-fixed-dim":          "#c8c6c5",
                "on-primary-fixed-variant":   "#474646",
                "surface-variant":            "#e4e2e2",
                "inverse-surface":            "#303031",
                "surface-bright":             "#fbf9f8",
                "tertiary-container":         "#261900",
                "primary-fixed":              "#e5e2e1",
                "on-primary-fixed":           "#1c1b1b",
                "secondary":                  "#5e5f5c",
                "tertiary-fixed":             "#ffdea5",
                "secondary-fixed-dim":        "#c7c6c4",
                "on-surface":                 "#1b1c1c",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg:      "16px",
                xl:      "24px",
                full:    "9999px",
            },
            spacing: {
                "section-gap":      "96px",
                "margin-desktop":   "64px",
                "margin-mobile":    "20px",
                "container-max":    "1280px",
                "gutter":           "28px",
                "unit":             "8px",
                "margin-tablet":    "32px",
            },
            fontFamily: {
                "body-md":              ["Inter"],
                "headline-lg":          ["Playfair Display"],
                "display-sm":           ["Playfair Display"],
                "headline-md":          ["Playfair Display"],
                "body-lg":              ["Inter"],
                "caption":              ["Inter"],
                "label-md":             ["Inter"],
                "display-lg":           ["Playfair Display"],
                "headline-lg-mobile":   ["Playfair Display"],
            },
            fontSize: {
                "body-md":            ["16px", { lineHeight: "1.6",  fontWeight: "400" }],
                "headline-lg":        ["32px", { lineHeight: "1.3",  fontWeight: "500" }],
                "display-sm":         ["48px", { lineHeight: "1.2",  fontWeight: "600" }],
                "headline-md":        ["24px", { lineHeight: "1.4",  fontWeight: "500" }],
                "body-lg":            ["18px", { lineHeight: "1.6",  fontWeight: "400" }],
                "caption":            ["12px", { lineHeight: "1.4",  fontWeight: "400" }],
                "label-md":           ["14px", { lineHeight: "1",    letterSpacing: "0.05em", fontWeight: "600" }],
                "display-lg":         ["64px", { lineHeight: "1.1",  letterSpacing: "-0.02em", fontWeight: "600" }],
                "headline-lg-mobile": ["28px", { lineHeight: "1.3",  fontWeight: "500" }],
            },
        },
    },
};
